### ISSUE TITLE
Support for Custom ESXi Images

### ISSUE THREAD

**Issue by wcs-bjogus** [laidbackware/vmd#1]
Addins support for downloading ex HPE custom images would be amazing.

ex:
https://www.hpe.com/us/en/servers/hpe-esxi.html 
https://customerconnect.vmware.com/en/downloads/details?downloadGroup=OEM-ESXI70U3-HPE&productId=974

**Comment by laidbackware** [comment]
Apologies for the super late response! It's not something I have time to do, but in theory it should be possible by updating the [SDK](https://github.com/vmware-labs/vmware-customer-connect-sdk/blob/main/sdk/subproducts.go) to try to download with the arg as [dlgType=CUSTOM_ISO](https://github.com/vmware-labs/vmware-customer-connect-sdk/blob/50e884bb647ef918700a83b64c75f0e4df9f8741/sdk/dlg_list.go#L39) and concatenate that with the binaries.

**Comment by laidbackware** [comment]
Hi @wcs-bjogus FYI your feature request is being worked on under the new location for this tool [https://github.com/vmware-labs/vmware-customer-connect-cli/issues/5](https://github.com/vmware-labs/vmware-customer-connect-cli/issues/5).
